### ISSUE TITLE
Run flake8 in TravisCI

### ISSUE THREAD

**Issue by ahal** [bclary/mozilla-bitbar-devicepool#3]
Would be nice to stand up at least flake8 for now in TravisCI. You can use https://github.com/mozilla/active-data-recipes as a template:

1. Copy the 'testenv:flake8' parts of the tox.ini (the import-order stuff is optional)
2. Install tox locally (`pip install tox`) and make sure that running `tox` causes flake8 to run
3. Copy .travis.yml (modifying to python 2 if needed)
4. Go to travics-ci.org, login with Github and find this repo and flick the switch

Once that's running, it'll be easy to add other steps to tox (e.g pytest) which will then automatically also run in TravisCI.

**Comment by ahal** [comment]
Also `autopep8` will fix most of the lint issues that flake8 detects.

**Comment by aerickson** [comment]
Fixed in #129.
